lesson_3
nikolay24534/PY200_Spring_2021 pull request #1
Opened 2021-02-07 17:25 UTC by nikolay24534

Безверхний Н.О.

Рабочий вариант. Не понимаю почему в таком виде метод clear что-то уд…аляет.

2021-02-09 16:31 UTC, aeksei commented on lesson_3/linked_list.py
> +        def next(self, next_: Optional['LinkedList.Node']):
Благодарю, не обращал на это внимания.
Буду иметь ввиду

2021-02-09 16:33 UTC, aeksei commented on lesson_3/linked_list.py
> +            current_node = current_node.next
Я бы это вынес в отдельный встроенный метод. Меньше дубляжа кода, легче поддерживать

2021-02-09 16:52 UTC, aeksei requested changes
Оставил комментарий по поводу метода `index`. Интересно было бы услышать ваше мнение на этот счёт. Если хотите можем на ближайшей практике обсудить этот момент.
Думаю и вам и вашим одногруппникам полезно будет это услышать))

2021-02-09 16:52 UTC, aeksei commented on lesson_3/linked_list.py
> +                return i
Можно объединить в один цикл, тогда надо сначала проверить условие, а потом `current_node = current_node.next`

2021-02-09 16:52 UTC, aeksei commented on lesson_3/linked_list.py
> +                return i
Если бы я вам задал вопрос, почему вы пошли по такому пути. А не воспользовались элегантной конструкцией:
```python
for i, node_value in enumerate(self):
    if node_value == value:
        return i
```
Cмогли бы вы аргументировать свою точку зрения? 
И доказать, что ваша реализация эффективнее или нет?

2021-02-10 10:14 UTC, nikolay24534 commented on lesson_3/linked_list.py
> +                return i
Думаю, что не смог бы.
Не доудмался до такой реализации потому что не воспринимал linkedlist, как объект к которому можно применть enumerate(). А даже если бы воспринимал, то вряд ли бы додумлася, что enumerate() нужно передать self.
Как-то не очевидно.
enumerate будет работать для объекта при том же условии, что и цикл for? Если правильно определен getitem ?

2021-02-10 10:15 UTC, nikolay24534 commented on lesson_3/linked_list.py
> +            current_node = current_node.next
Понятно, исправлю

2021-02-10 14:03 UTC, aeksei commented on lesson_3/linked_list.py
> +                return i
реализовав верно getitem, LinkedList ведет себя схоже с обычным python списком, а если в общем смысле, то с последовательностями

2021-02-16 13:45 UTC, merged